### ISSUE TITLE
Error message in combineAnnotatePeaks

### ISSUE THREAD

**Issue by Dazcam** [Mathelab/ALTREsampledata#2]
I've encountered the following error message when trying to run combineAnnotatePeaks using the default settings from the vignette:

```
Error in `[[<-`(`*tmp*`, name, value = c("TSS-proximal", "TSS-distal",  : 
  203197 elements in value to replace 205074 elements
In addition: Warning message:
In .Seqinfo.mergexy(x, y) :
  Each of the 2 combined objects has sequence levels not in the other:
  - in 'x': chr1_gl000191_random, chr1_gl000192_random, chr4_ctg9_hap1, chr4_gl000193_random, chr4_gl000194_random, chr6_apd_hap1, chr6_cox_hap2, chr6_dbb_hap3, chr6_mann_hap4, chr6_mcf_hap5, chr6_qbl_hap6, chr6_ssto_hap7, chr7_gl000195_random, chr8_gl000196_random, chr8_gl000197_random, chr9_gl000198_random, chr9_gl000200_random, chr9_gl000201_random, chr11_gl000202_random, chr17_ctg5_hap1, chr17_gl000204_random, chr17_gl000205_random, chr17_gl000206_random, chr21_gl000210_random, chrUn_gl000211, chrUn_gl000212, chrUn_gl000214, chrUn_gl000216, chrUn_gl000217, chrUn_gl000218, chrUn_gl000219, chrUn_gl000220, chrUn_gl000221, chrUn_gl000222, chrUn_gl000223, chrUn_gl000224, chrUn_gl000225, chrUn_gl000227, chrUn_gl000228, chrUn_gl000229, chrUn_gl000231, chrUn_gl000232, chrUn_gl000234, chrUn_gl000235, chrUn_gl000237, chrUn_gl000239, chrUn_gl000241, chrUn_gl000242, chrUn_gl000243, chrUn_gl000245, chrUn_gl000247, chr19_gl0002 [... truncated]
```

My data is aligned to hg19. I suspect that this has something to do with the TSS bed file. 

Initially I created the TSS bed file from the GTF file you provided using your perl script but that led to the error above. 

I then tried to create my own TSS bed file via the UCSC table browser using the ensemble gene set. But this threw the same error with the only difference being in the second line:

`204809 elements in value to replace 205074 elements`

Not sure how to rectify this. Any advice would be greatly appreciated.

**Comment by ewymathe** [comment]
Thank you for raising this issue.  Will get back to you shortly.

**Comment by ewymathe** [comment]
I do not think that hg19 is the issue.  Could you double check whether your peak files have chromosomes other than chr1-22, X, and Y?  I was able to replicate a similar error when my peaks had chromosomes outside that range.
ALTRE only retrieves annotations for chr1-22, X, Y.  Please let me know if you wish to look at additional annotated chromosomes.

**Comment by Dazcam** [comment]
Thanks for the response. 

I have just managed to get this working. 

However, I had to remove the extraneous chromosome annotations from the peak file, the TSS bed file and remove the reads mapped to extraneous chromosomes from the bam file before it worked.  

Thanks for you help.

**Comment by Mathelab** [comment]
Glad it's working.  I've updated the README file in the IntLIM package to help avoid this issue in the future.
